services:
  - type: web
    name: promptgen-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
      - key: GEMINI_API_KEY
        sync: false
